import { describe, expect, it } from 'bun:test'
import { normalizeSessions } from '~/utils/normalizeSessions'

describe('normalizeSessions()', () => {
  it('works', () => {
    const raw: Record<string, string>[] = [
      {},
      {
        id: '1',
        title_zh: '第一個 Session',
        title_en: 'First Session',
        description_zh: '這是第一個 Session',
        description_en: 'This is the first Session',
        type: 'P',
        room: 'R2',
        broadcast: 'https://example.com/broadcast/1',
        start: '2024-05-04T15:50:00+08:00',
        end: '2024-05-04T17:20:00+08:00',
        speaker1id: 'zh-1',
        speaker1: '講師一',
        speaker2id: 'zh-2',
        speaker2: '講師二',
        speaker3id: '',
        speaker3: '',
        speaker4id: '',
        speaker4: '',
        speaker5id: '',
        speaker5: '',
        qa: 'https://example.com/qa/1',
        slide: 'https://example.com/slide/1',
        tag1: 'tag1',
        tag2: 'tag2',
        tag3: '',
        tag4: '',
        tag5: '',
        tag6: '',
        tag7: '',
        tag8: '',
        tag9: '',
        co_write: 'https://example.com/co_write/1',
        live: 'https://example.com/live/1',
        record: 'https://example.com/record/1',
        language: 'zh',
        uri: 'https://example.com/sesssion/1',
      },
      {
        id: '2',
        title_zh: '第二個 Session',
        title_en: 'Second Session',
        description_zh: '這是第二個 Session',
        description_en: 'This is the second Session',
        type: 'P',
        room: 'R2',
        broadcast: 'https://example.com/broadcast/2',
        start: '2024-05-04T15:50:00+08:00',
        end: '2024-05-04T17:20:00+08:00',
        speaker1id: 'zh-3',
        speaker1: '講師三',
        speaker2id: 'zh-4',
        speaker2: '講師四',
        speaker3id: '',
        speaker3: '',
        speaker4id: '',
        speaker4: '',
        speaker5id: '',
        speaker5: '',
        qa: 'https://example.com/qa/2',
        slide: 'https://example.com/slide/2',
        tag1: 'tag3',
        tag2: 'tag4',
        tag3: '',
        tag4: '',
        tag5: '',
        tag6: '',
        tag7: '',
        tag8: '',
        tag9: '',
        co_write: 'https://example.com/co_write/2',
        live: 'https://example.com/live/2',
        record: 'https://example.com/record/2',
        language: 'zh',
        uri: 'https://example.com/sesssion/2',
      },
    ]

    expect(normalizeSessions(raw)).toEqual([
      {
        id: '1',
        type: 'P',
        room: 'R2',
        broadcast: 'https://example.com/broadcast/1',
        start: '2024-05-04T15:50:00+08:00',
        end: '2024-05-04T17:20:00+08:00',
        qa: 'https://example.com/qa/1',
        slide: 'https://example.com/slide/1',
        co_write: 'https://example.com/co_write/1',
        live: 'https://example.com/live/1',
        record: 'https://example.com/record/1',
        language: 'zh',
        uri: 'https://example.com/sesssion/1',
        zh: {
          title: '第一個 Session',
          description: '這是第一個 Session',
        },
        en: {
          title: 'First Session',
          description: 'This is the first Session',
        },
        speakers: ['zh-1', 'zh-2'],
        tags: ['tag1', 'tag2'],
      },
      {
        id: '2',
        type: 'P',
        room: 'R2',
        broadcast: 'https://example.com/broadcast/2',
        start: '2024-05-04T15:50:00+08:00',
        end: '2024-05-04T17:20:00+08:00',
        qa: 'https://example.com/qa/2',
        slide: 'https://example.com/slide/2',
        co_write: 'https://example.com/co_write/2',
        live: 'https://example.com/live/2',
        record: 'https://example.com/record/2',
        language: 'zh',
        uri: 'https://example.com/sesssion/2',
        zh: {
          title: '第二個 Session',
          description: '這是第二個 Session',
        },
        en: {
          title: 'Second Session',
          description: 'This is the second Session',
        },
        speakers: ['zh-3', 'zh-4'],
        tags: ['tag3', 'tag4'],
      },
    ])
  })

  it('skip first item', () => {
    const raw: Record<string, string>[] = [{}]
    expect(normalizeSessions(raw).length).toBe(0)
  })

  it('works with some empty fields', () => {
    const raw: Record<string, string>[] = [
      {},
      {
        id: '1',
        title_zh: '第一個 Session',
        title_en: '',
        description_zh: '這是第一個 Session',
        description_en: '',
        type: 'P',
        room: 'R2',
        broadcast: '',
        start: '2024-05-04T15:50:00+08:00',
        end: '2024-05-04T17:20:00+08:00',
        speaker1id: 'zh-1',
        speaker1: '講師一',
        speaker2id: '',
        speaker2: '',
        speaker3id: '',
        speaker3: '',
        speaker4id: '',
        speaker4: '',
        speaker5id: '',
        speaker5: '',
        qa: 'https://example.com/qa/1',
        slide: 'https://example.com/slide/1',
        tag1: 'tag1',
        tag2: '',
        tag3: '',
        tag4: '',
        tag5: '',
        tag6: '',
        tag7: '',
        tag8: '',
        tag9: '',
        co_write: 'https://example.com/co_write/1',
        live: '',
        record: 'https://example.com/record/1',
        language: 'zh',
        uri: 'https://example.com/sesssion/1',
      },
    ]

    expect(normalizeSessions(raw)).toEqual([
      {
        id: '1',
        type: 'P',
        room: 'R2',
        broadcast: '',
        start: '2024-05-04T15:50:00+08:00',
        end: '2024-05-04T17:20:00+08:00',
        qa: 'https://example.com/qa/1',
        slide: 'https://example.com/slide/1',
        co_write: 'https://example.com/co_write/1',
        live: '',
        record: 'https://example.com/record/1',
        language: 'zh',
        uri: 'https://example.com/sesssion/1',
        zh: {
          title: '第一個 Session',
          description: '這是第一個 Session',
        },
        en: {
          title: '',
          description: '',
        },
        speakers: ['zh-1'],
        tags: ['tag1'],
      },
    ])
  })

  it('works with some fields missing', () => {
    const raw: Record<string, string>[] = [
      {},
      {
        id: '1',
        title_zh: '第一個 Session',
        description_zh: '這是第一個 Session',
        type: 'P',
        room: 'R2',
        broadcast: '',
        start: '2024-05-04T15:50:00+08:00',
        end: '2024-05-04T17:20:00+08:00',
        speaker1id: 'zh-1',
        speaker1: '講師一',
        speaker2id: '',
        speaker2: '',
        speaker3id: '',
        speaker3: '',
        speaker4id: '',
        speaker4: '',
        speaker5id: '',
        speaker5: '',
        qa: 'https://example.com/qa/1',
        slide: 'https://example.com/slide/1',
        tag1: 'tag1',
        tag2: '',
        tag3: '',
        tag4: '',
        tag5: '',
        tag6: '',
        tag7: '',
        tag8: '',
        tag9: '',
        co_write: 'https://example.com/co_write/1',
        live: '',
        record: 'https://example.com/record/1',
        language: 'zh',
        uri: 'https://example.com/sesssion/1',
      },
    ]

    expect(normalizeSessions(raw)).toEqual([
      {
        id: '1',
        type: 'P',
        room: 'R2',
        broadcast: '',
        start: '2024-05-04T15:50:00+08:00',
        end: '2024-05-04T17:20:00+08:00',
        qa: 'https://example.com/qa/1',
        slide: 'https://example.com/slide/1',
        co_write: 'https://example.com/co_write/1',
        live: '',
        record: 'https://example.com/record/1',
        language: 'zh',
        uri: 'https://example.com/sesssion/1',
        zh: {
          title: '第一個 Session',
          description: '這是第一個 Session',
        },
        en: {
          title: '',
          description: '',
        },
        speakers: ['zh-1'],
        tags: ['tag1'],
      },
    ])
  })

  it('works with no input', () => {
    expect(normalizeSessions()).toEqual([])
  })

  it('gets all speakers', () => {
    const raw: Record<string, string>[] = [
      {},
      {
        id: '1',
        title_zh: '第一個 Session',
        title_en: 'First Session',
        description_zh: '這是第一個 Session',
        description_en: 'This is the first Session',
        type: 'P',
        room: 'R2',
        broadcast: 'https://example.com/broadcast/1',
        start: '2024-05-04T15:50:00+08:00',
        end: '2024-05-04T17:20:00+08:00',
        speaker1id: 'zh-1',
        speaker1: '講師一',
        speaker2id: '',
        speaker2: '',
        speaker3id: 'zh-3',
        speaker3: '講師三',
        speaker4id: '',
        speaker4: '',
        speaker5id: 'zh-5',
        speaker5: '講師五',
        qa: 'https://example.com/qa/1',
        slide: 'https://example.com/slide/1',
        tag1: 'tag1',
        tag2: 'tag2',
        tag3: '',
        tag4: '',
        tag5: '',
        tag6: '',
        tag7: '',
        tag8: '',
        tag9: '',
        co_write: 'https://example.com/co_write/1',
        live: 'https://example.com/live/1',
        record: 'https://example.com/record/1',
        language: 'zh',
        uri: 'https://example.com/sesssion/1',
      },
    ]

    expect(normalizeSessions(raw)).toEqual([
      {
        id: '1',
        type: 'P',
        room: 'R2',
        broadcast: 'https://example.com/broadcast/1',
        start: '2024-05-04T15:50:00+08:00',
        end: '2024-05-04T17:20:00+08:00',
        qa: 'https://example.com/qa/1',
        slide: 'https://example.com/slide/1',
        co_write: 'https://example.com/co_write/1',
        live: 'https://example.com/live/1',
        record: 'https://example.com/record/1',
        language: 'zh',
        uri: 'https://example.com/sesssion/1',
        zh: {
          title: '第一個 Session',
          description: '這是第一個 Session',
        },
        en: {
          title: 'First Session',
          description: 'This is the first Session',
        },
        speakers: ['zh-1', 'zh-3', 'zh-5'],
        tags: ['tag1', 'tag2'],
      },
    ])
  })

  it('gets all tags', () => {
    const raw: Record<string, string>[] = [
      {},
      {
        id: '1',
        title_zh: '第一個 Session',
        title_en: 'First Session',
        description_zh: '這是第一個 Session',
        description_en: 'This is the first Session',
        type: 'P',
        room: 'R2',
        broadcast: 'https://example.com/broadcast/1',
        start: '2024-05-04T15:50:00+08:00',
        end: '2024-05-04T17:20:00+08:00',
        speaker1id: 'zh-1',
        speaker1: '講師一',
        speaker2id: 'zh-2',
        speaker2: '講師二',
        speaker3id: '',
        speaker3: '',
        speaker4id: '',
        speaker4: '',
        speaker5id: '',
        speaker5: '',
        qa: 'https://example.com/qa/1',
        slide: 'https://example.com/slide/1',
        tag1: 'tag1',
        tag2: 'tag2',
        tag3: '',
        tag4: '',
        tag5: 'tag5',
        tag6: '',
        tag7: 'tag7',
        tag8: '',
        tag9: 'tag9',
        co_write: 'https://example.com/co_write/1',
        live: 'https://example.com/live/1',
        record: 'https://example.com/record/1',
        language: 'zh',
        uri: 'https://example.com/sesssion/1',
      },
    ]

    expect(normalizeSessions(raw)).toEqual([
      {
        id: '1',
        type: 'P',
        room: 'R2',
        broadcast: 'https://example.com/broadcast/1',
        start: '2024-05-04T15:50:00+08:00',
        end: '2024-05-04T17:20:00+08:00',
        qa: 'https://example.com/qa/1',
        slide: 'https://example.com/slide/1',
        co_write: 'https://example.com/co_write/1',
        live: 'https://example.com/live/1',
        record: 'https://example.com/record/1',
        language: 'zh',
        uri: 'https://example.com/sesssion/1',
        zh: {
          title: '第一個 Session',
          description: '這是第一個 Session',
        },
        en: {
          title: 'First Session',
          description: 'This is the first Session',
        },
        speakers: ['zh-1', 'zh-2'],
        tags: ['tag1', 'tag2', 'tag5', 'tag7', 'tag9'],
      },
    ])
  })
})
